name: Build and release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '17' ]

    name: Build on Java ${{ matrix.java }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress package

  release:
    runs-on: ubuntu-latest
    needs: build

    name: Release on Java 11
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
          cache: 'maven'
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Resolve version and set version with Maven
        run: |
          if [[ $GITHUB_REF == *"tags"* ]]; then
            export RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          else
            export RELEASE_VERSION=${GITHUB_REF#refs/heads/}-SNAPSHOT
          fi
          mvn versions:set --no-transfer-progress -DnewVersion=$RELEASE_VERSION
      - name: Deploy with Maven
        run: mvn clean deploy --settings '.mvn/settings.xml' -P build-javadoc-and-sources,release -Dmaven.test.skip=true --batch-mode --no-transfer-progress
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
